spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        '[show_sql]': true        
        '[format_sql]': true        
    database-platform: org.hibernate.dialect.H2Dialect   

logging:
  level:
    '[org.springframework.web]': DEBUG
    '[org.hibernate]': ERROR

server: 
  servlet:    
    context-path: /api/v1
  port: 8080

springdoc:
  packagesToScan: com.texoit.moviesapi.controller
  swagger-ui:
    doc-expansion: none